/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wuyunpeng_facevertificationultimate_AlogrithmFromCpp */

#ifndef _Included_com_example_wuyunpeng_facevertificationultimate_AlogrithmFromCpp
#define _Included_com_example_wuyunpeng_facevertificationultimate_AlogrithmFromCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wuyunpeng_facevertificationultimate_AlogrithmFromCpp
 * Method:    getFeatureVctor
 * Signature: ([III)[F
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_wuyunpeng_facevertificationultimate_AlogrithmFromCpp_getResizeImage
  (JNIEnv * env, jclass obj, jintArray imageData, jint w, jint h);


JNIEXPORT jboolean JNICALL Java_com_example_wuyunpeng_facevertificationultimate_AlogrithmFromCpp_getFaceDetection
        (JNIEnv * env, jclass obj, jintArray imageData,jint w, jint h,jstring xmlStr);
#ifdef __cplusplus
}
#endif
#endif
